// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcpfMinoaeWM-dDpS8jxt0eeCv_zNm3bE',
    appId: '1:360344705913:web:074abc7dbd2abeb42f6da8',
    messagingSenderId: '360344705913',
    projectId: 'admiserv-7e60d',
    authDomain: 'admiserv-7e60d.firebaseapp.com',
    storageBucket: 'admiserv-7e60d.appspot.com',
    measurementId: 'G-LFKLEKQ2LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQNT00u_EUEkBf57L6woZ4-4OnacIgpk',
    appId: '1:360344705913:android:78bc41e4ec5b6d752f6da8',
    messagingSenderId: '360344705913',
    projectId: 'admiserv-7e60d',
    storageBucket: 'admiserv-7e60d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmQGTvSSX3AyGJjn_hYu3dDFmVXUgR--w',
    appId: '1:360344705913:ios:0f546644c0c52abf2f6da8',
    messagingSenderId: '360344705913',
    projectId: 'admiserv-7e60d',
    storageBucket: 'admiserv-7e60d.appspot.com',
    iosBundleId: 'cruzbrito.carloseduardo.admiservAdm',
  );
}
